# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QZDWB11H_sE8VyfQCJaDldLMy9uFLqpu
"""

import pandas as pd

def load_data():
  url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
  html = pd.read_html(url, header = 0)
  df = html[0]
  return df

df = load_data()
df

unique_sectors = df['GICS Sector'].unique()
unique_sectors

sector = df.groupby('GICS Sector')
sector.first()

sector.describe()

sector.get_group('Health Care')

pip install yfinance

import yfinance as yf
list(df.Symbol)

data = yf.download(  # or pdr.get_data_yahoo(...
        # tickers list or string as well
        tickers = "TSLA",

        # use "period" instead of start/end
        # valid periods: 1d,5d,1mo,3mo,6mo,1y,2y,5y,10y,ytd,max
        # (optional, default is '1mo')
        period = "1y",

        # fetch data by interval (including intraday if period < 60 days)
        # valid intervals: 1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo
        # (optional, default is '1d')
        interval = "1mo",

        # group by ticker (to access via data['SPY'])
        # (optional, default is 'column')
        group_by = 'ticker',

        # adjust all OHLC automatically
        # (optional, default is False)
        auto_adjust = False,

        # download pre/post regular market hours data
        # (optional, default is False)
        prepost = False,

        # use threads for mass downloading? (True/False/Integer)
        # (optional, default is True)
        threads = True,

        # proxy URL scheme use use when downloading?
        # (optional, default is None)
        proxy = None
    )

data

df1 = pd.DataFrame(data.Close)

df1['Date'] = df1.index
df1

import matplotlib.pyplot as plt
plt.fill_between(df1.Date, df1.Close, color = "skyblue", alpha = 0.3)
plt.plot(df1.Date, df1.Close, color = "skyblue", alpha = 0.8)
plt.xticks(rotation = 80)
plt.xlabel('Date')
plt.ylabel('Closing Price')